version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8086:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
# BOILERPLATE CODE PROVIDED BY AP CSP TEACHER then modified to fit CPT project needs